### ISSUE TITLE
Page doesn't fully load

### ISSUE THREAD

**Issue by ollien** [radiant-player/radiant-player-mac#572]
I'm on 1.8.4 and whenever I open Radiant, it opens to something like this. 
![screen shot 2016-07-25 at 9 46 21 pm](https://cloud.githubusercontent.com/assets/977151/17123407/4b2b8478-52b1-11e6-816c-62137e7f6882.png)

I checked the javascript console and found a plethora of errors.
![screen shot 2016-07-25 at 9 44 57 pm](https://cloud.githubusercontent.com/assets/977151/17123397/40812ea6-52b1-11e6-9c53-2338881d4a77.png)

The page loads fine in Chrome 52.

**Comment by jacobwgillespie** [comment]
Looks like an issue on Google's end.  Can you open Google Music in Safari, clear the cache, and validate that it works correctly in Safari?

My guess is it's a temporary thing that will resolve itself, but I can take a look.

**Comment by ollien** [comment]
Works fine in Safari 9.1.

**Comment by rickarubio** [comment]
I'm on Radiant Player v1.8.4 and also seeing this issue.

<img width="1435" alt="screen shot 2016-07-26 at 11 12 36 am" src="https://cloud.githubusercontent.com/assets/3452670/17149880/0ef27fa4-5322-11e6-8317-a0905281113d.png">

**Comment by rickarubio** [comment]
Safari 9.1.2 is working and console logs look like this:

<img width="1161" alt="screen shot 2016-07-26 at 11 27 08 am" src="https://cloud.githubusercontent.com/assets/3452670/17150365/fa9e29c0-5323-11e6-990c-7a39983225b3.png">

Looks like the same as inside the Radiant player app except that there are no page breaking "HTMLScriptElement is not a function" errors when using the browser.

**Comment by jacobwgillespie** [comment]
Yep, my app just restarted and I'm experiencing the same issue.  I'll do some digging.

**Comment by seniortwinkie** [comment]
Unfortunately, I am also getting that error.
![screen shot 2016-07-26 at 11 37 55 am](https://cloud.githubusercontent.com/assets/3770266/17150745/7573fee4-5325-11e6-8c57-b243ed6fbdb1.png)

**Comment by jacobg** [comment]
me too

**Comment by jacobwgillespie** [comment]
Found the fix (it's an issue in Radiant's code that happened to conflict with Google's update).  As soon as #573 gets reviewed and merged I'll push out a release.

**Comment by jacobwgillespie** [comment]
This is fixed in `1.8.5` which will automatically release in the next few minutes.
